In [17]:
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = ""

import numpy as np
from keras.models import load_model

model_file_path = '/home/greghovhannisyan/PycharmProjects/289N_Protein_SS_Prediction/saved_models/cnn_model_val_0.0404.h5'
data_file_path = '/home/greghovhannisyan/PycharmProjects/289N_Protein_SS_Prediction/Data/cullpdb+profile_6133.npy.gz'

my_data = np.load(data_file_path)
my_model = load_model(model_file_path)

reshaped_data = np.reshape(my_data, (6133,700,57,1))
X_Train = reshaped_data[:,:,0:22, :]
Y_Train = reshaped_data[:,:,22:31, :]

predictions  = my_model.predict(X_Train[:,:,:,:])


In [2]:
predictions[0][0].shape

(9, 1)

In [21]:
import tensorflow as tf
a = tf.convert_to_tensor(Y_Train)

In [35]:
int(a.shape[0])

6133

In [3]:
predictions[0][5]

array([[0.03606068],
       [0.        ],
       [0.35171577],
       [0.        ],
       [0.09427586],
       [0.23466042],
       [0.        ],
       [0.        ],
       [0.        ]], dtype=float32)

In [22]:
Y_Train[0][1]

array([[0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [6]:
np.argmax(predictions[0][0])

6

In [15]:
predictions[0][0]

array([1.4914745e-01, 0.0000000e+00, 0.0000000e+00, 3.3899263e-02,
       3.9462745e-04, 4.4839233e-01, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00], dtype=float32)

In [18]:
total_counter = 0
protein_error_list = list()
protein_error_counter = 0
t = Y_Train[6001:6133,:,:]

for i in range(132):
    aa_error_counter = 0
    protein_error_list.append(list())
    for j in range(700):
        if(np.argmax(t[i][j][:]) != 8):
            total_counter += 1
            if(np.argmax(predictions[i][j][:]) != np.argmax(t[i][j][:])):
                #print(np.argmax(predictions[i][j][:]), np.argmax(t[i][j][:]))
                protein_error_list[i].append(1)            


total_error = 0
for val in protein_error_list:
    total_error += len(val)

print(total_error)
print(total_counter)


23324
29187


In [19]:
accuracy = (total_counter-total_error)/total_counter
print('Accuracy is ' + str(accuracy))

Accuracy is 0.20087710281974852
