In [1]:
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = ""

import numpy as np
from keras.models import load_model

model_file_path = '/home/greghovhannisyan/PycharmProjects/289N_Protein_SS_Prediction/saved_models/fc_model_44_params_val_0.0223.h5'
data_file_path = '/home/greghovhannisyan/PycharmProjects/289N_Protein_SS_Prediction/Data/cullpdb+profile_6133.npy.gz'

my_data = np.load(data_file_path)
my_model = load_model(model_file_path)

reshaped_data = np.reshape(my_data, (6133,700,57))
X_Train = np.concatenate((reshaped_data[:,:,0:22],reshaped_data[:,:,35:57]), axis=2)
Y_Train = reshaped_data[:,:,22:31]

predictions  = my_model.predict(X_Train[5001:6133,:,:])


/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [16]:
np.concatenate((reshaped_data[:,:,0:22],reshaped_data[:,:,35:57]), axis=2).shape

(6133, 700, 44)

In [11]:
predictions[0][0].shape

(9,)

In [24]:
t = Y_Train[6001:6133,:,:]
t[0][600]

array([0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [4]:
predictions[0][5]

array([0.17588595, 0.00670674, 0.15877554, 0.04365741, 0.00194273,
       0.43120855, 0.07920985, 0.10161977, 0.00099343], dtype=float32)

In [22]:
Y_Train[0][1]

array([[0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [6]:
np.argmax(predictions[0][0])

6

In [15]:
predictions[0][0]

array([1.4914745e-01, 0.0000000e+00, 0.0000000e+00, 3.3899263e-02,
       3.9462745e-04, 4.4839233e-01, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00], dtype=float32)

In [2]:
total_counter = 0
protein_error_list = list()
protein_error_counter = 0
t = Y_Train[5001:6133,:,:]

for i in range(len(t)):
    aa_error_counter = 0
    protein_error_list.append(list())
    for j in range(700):
        if(np.argmax(t[i][j][:]) != 8):
            total_counter += 1
            if(np.argmax(predictions[i][j][:]) != np.argmax(t[i][j][:])):
                #print(np.argmax(predictions[i][j][:]), np.argmax(t[i][j][:]))
                protein_error_list[i].append(1)            


total_error = 0
for val in protein_error_list:
    total_error += len(val)

print(total_error)
print(total_counter)


126846
237078


In [3]:
accuracy = (total_counter-total_error)/total_counter
print('Accuracy is ' + str(accuracy))

Accuracy is 0.46496089894465115
